# Generated by Django 4.0 on 2022-01-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_image_image_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_content',
            field=models.ImageField(upload_to='profilepic/'),
        ),
    ]
